version: '3.8'


services:
  mysql:
    build: ./db/
    container_name: bdd_projet
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bdd_projet
  api:
    build: ./src/
    container_name: api_projet
    ports:
      - 85:5000
      
